version: "2.1"
services:
  app:
    build: .
    command: npm test
    volumes:
    - .:/output
    environment:
    - NODE_ENV=test
    - MONGODB=mongodb://mongodb:27017/test
    - ES=http://es:9200
    depends_on:
      mongodb:
        condition: service_healthy
      es:
        condition: service_healthy
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
    - http.cors.enabled=true
    - xpack.security.enabled=false
    - http.port=9200
    - http.cors.allow-origin=*
    - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type, Content-Length, Authorization
    - http.cors.allow-credentials=true
    ports:
    - "9200:9200"
    healthcheck:
      test: curl --silent --fail localhost:9200/_cluster/health
      interval: 10s
      retries: 6
  mongodb:
    image: mongo:4
    ports:
    - "27017:27017"
    healthcheck:
      test: mongo localhost:27017 --eval "db.version()"
      interval: 10s
      retries: 6
